### ISSUE TITLE
Documenting reasons for not using MRJARs

### ISSUE THREAD

**Issue by JordanMartinez** [melix/mrjar-gradle#1]
It says in the ReadMe

> MRJARs are a very wrong abstraction for a real problem. We will come with more details about why. If you still insist on creating one, here's how you can do it with Gradle.

If this has already been documented, where is it? If not, when and where will it be documented?

**Comment by pioterj** [comment]
@JordanMartinez You can find the reasoning behind it in this blog post: https://blog.gradle.org/mrjars.

@melix It would be good to add the link to the blog post in the readme.

**Comment by melix** [comment]
@pioterj done, thanks!

**Comment by JordanMartinez** [comment]
Thanks! That clarifies it a lot!
